/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WizardsRouteImport } from './routes/wizards/route'
import { Route as HousesRouteImport } from './routes/houses/route'
import { Route as WizardsCreateImport } from './routes/wizards/create'
import { Route as WizardsIdImport } from './routes/wizards/$id'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const WizardsRouteRoute = WizardsRouteImport.update({
  path: '/wizards',
  getParentRoute: () => rootRoute,
} as any)

const HousesRouteRoute = HousesRouteImport.update({
  path: '/houses',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const WizardsCreateRoute = WizardsCreateImport.update({
  path: '/create',
  getParentRoute: () => WizardsRouteRoute,
} as any)

const WizardsIdRoute = WizardsIdImport.update({
  path: '/$id',
  getParentRoute: () => WizardsRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/houses': {
      preLoaderRoute: typeof HousesRouteImport
      parentRoute: typeof rootRoute
    }
    '/wizards': {
      preLoaderRoute: typeof WizardsRouteImport
      parentRoute: typeof rootRoute
    }
    '/wizards/$id': {
      preLoaderRoute: typeof WizardsIdImport
      parentRoute: typeof WizardsRouteImport
    }
    '/wizards/create': {
      preLoaderRoute: typeof WizardsCreateImport
      parentRoute: typeof WizardsRouteImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  HousesRouteRoute,
  WizardsRouteRoute.addChildren([WizardsIdRoute, WizardsCreateRoute]),
])

/* prettier-ignore-end */
